spring:
  datasource:
    password: Pass1234
    username: postgres
    url: jdbc:postgresql://localhost:5432/teazy
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  liquibase:
    enabled: false
    change-log: classpath:liquibase/changelog-master.yml

minio:
  url: http://172.17.0.3:9000
  bucket: teazy
  access-key: minio
  secret-key: minio1234
  image-folder: profpic/
  video-folder: video/

file:
  upload:
    acceptableVideoExtensions: mp4,mov,avi,wmv
    acceptableImageExtensions: jpg,png,jpeg

saleType:
  upload:
    acceptableSaleType: bolt,wolt,teazy

img:
  width: 2560
  height: 1000
  divide: 3